a# Generated by Django 4.1.7 on 2023-02-25 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('first_login', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('logged', models.BooleanField(default=False, help_text='If otp verification got successful')),
                ('count', models.IntegerField(default=0, help_text='Number of otp sent')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.BooleanField(default=False)),
                ('user', models.BooleanField(default=True)),
                ('doctor', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
